image: reg-gitlab.btcbit.loc:3343/gitops/repos/docker-images/cicd-php82-node:1.0.0

stages:
  - code-check
  - test

include:
  - project: 'system/cd-templates'
    file:
      - code_review.yml
      - unit_test_sqlite.yml

variables:
  build: "build" ## npm_build, idk_build
  MODULE: "php-cs-fixer-config"
  PROJECT: "btc"
  RELEASE_INCLUDE_FOLDERS: "src vendor"
  SKIP_PHPSTAN: "false"
  SKIP_RECTOR: "true"
  SKIP_CS_CHECK: "false"
